services:
  superset:
    image: apache/superset
    container_name: superset_app
    environment:
      SUPERSET_SECRET_KEY: "CHANGE_SECRET_KEY"
      SUPERSET_DATABASE_URI: "sqlite:////app/superset_home/superset.db"
    ports:
      - "8088:8088"
    command:
      - /bin/sh
      - -c
      - |
        superset db upgrade &&
        superset init &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
        superset run -h 0.0.0.0 -p 8088

volumes:
  superset_home:
